export { info as bitcoin } from './bitcoin'
export { info as bitcoincash } from './bitcoincash'
export { info as bitcoinsv } from './bitcoinsv'
export { info as feathercoin } from './feathercoin'
export { info as litecoin } from './litecoin'
export { info as zcoin } from './zcoin'
